name: First Workflow
on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK 24
        uses: actions/setup-java@v4

      - name: Build
        run: gradle clean build
