name: Coffee-Machine Workflow
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        uses: actions/setup-java@v

      - name: Build
        run: gradlew clean build
